# Generated by Django 4.1.2 on 2022-10-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deskstatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='deskstatus',
            name='desk_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='deskstatus',
            name='desk_value',
            field=models.CharField(default='n', max_length=10, primary_key=True, serialize=False),
        ),
    ]
